[[headers]]
  for = "/assets/fonts.css"
  [headers.values]
    Access-Control-Allow-Origin = "https://www.reddit.com/"

[[headers]]
  for = "/fonts/web/full/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[build]
  base = ""
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "https://unnamed-sans.netlify.app/*"
  to = "https://redditsans.s-ings.com/:splat"
  status = 301
  force = true